# Generated by Django 4.2.4 on 2023-11-17 20:07

from django.db import migrations

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    # TODO add arches version dependency

    forward = """
        INSERT INTO plugins (
            pluginid, name, icon, component, componentname, config, slug, sortorder)
        VALUES (
            '9005c093-40ea-4507-96fe-61c1bdf96a19',
            '{"en": "Audit Dashboard"}',
            'fa fa-pie-chart',
            'views/components/plugins/audit',
            'audit', 
            '{"show": true, "is_workflow": false, "description": ""}',
            'audit',
            '1'
        );
        """
    
    reverse = """
        DELETE FROM plugins where pluginid = '9005c093-40ea-4507-96fe-61c1bdf96a19';
        """

    operations = [
        migrations.RunSQL(forward, reverse),
    ]
